### ISSUE TITLE
SPDX licence

### ISSUE THREAD

**Issue by fabianhussl** [nebulx29/MMM-bergfex#1]
Hi,
after installing I get an npm warning: 
`npm WARN MMM-bergfex@ license should be a valid SPDX license expression`
MMM-Bergfex doesn't load any skiing resorts.
Regards from the Bodensee,
Fabian

**Comment by fabianhussl** [comment]
Hi,
still have problems with this module.
Can you help me?
On the screen I get the header ("Gebiet Tal Berg Neu Lifte") but I just get the start sequence "loading......"
Regards,
Fabian

**Comment by ReinerZ** [comment]
1) add "private": true,  after "license": "Apache 2.0", inside package.json to avoid the license problem

2) change  inside node_helper.js
var sys = require('sys');    to
//var sys = require('sys');
var util = require('util');     

3) change  inside node_helper.js
var tbody = $('.content').children().last();   to
var tbody = $('.content>table').children().last();

regards
Reiner

**Comment by fabianhussl** [comment]
Hi @ReinerZ 
thank you for your help - the changes worked perfectly.
Regards,
Fabian

**Comment by ReinerZ** [comment]
:-)
