### ISSUE TITLE
Krimml / Hochkrimml - Zillertal Arena

### ISSUE THREAD

**Issue by Kevkop** [nebulx29/MMM-bergfex#3]
Hi,

If i try to ad the ski area Krimml / Hochkrimml - Zillertal Arena the module keeps loading.

This is working:
{
disabled: false,
module: “MMM-bergfex”,
position: “bottom_left”,
config: {
updateInterval: 30*60*1000,
animationSpeed: 0,
header: “SNEEUW in de ALPEN”,
skiareas: [
“Gerlos - Zillertal Arena”,
“Silvretta Montafon”,
],
shortenArea: 35,
cssclassrow: “normal”,
cssclassheader: “bright”
}
},

And this is not working:
{
disabled: false,
module: “MMM-bergfex”,
position: “bottom_left”,
config: {
updateInterval: 30*60*1000,
animationSpeed: 0,
header: “SNEEUW in de ALPEN”,
skiareas: [
“Gerlos - Zillertal Arena”,
“Silvretta Montafon”,
“Krimml / Hochkrimml - Zillertal Arena”,
],
shortenArea: 35,
cssclassrow: “normal”,
cssclassheader: “

I’ve tried different ways, with spaces, without, ... won’t work. Can somebody help me?

Thanks

**Comment by lxne** [comment]
I have the same problem with "Hochkar".
It worked for a while but doesn't right now.

**Comment by Kevkop** [comment]
Oh i solved my problem some time ago. Just went to bergfex website and copied the text Krimml Hochkrimml. Instead of Krimml - hochkrimml On the website it is Krimml — hochkrimml. Look well to small differences...

**Comment by Curtis777** [comment]
i dont even got the sample config to run ?
